language: node_js
node_js:
  - "9"
sudo: false
cache:
  yarn: true
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.4.0
  - export PATH=$HOME/.yarn/bin:$PATH
before_script:
  - yarn global add lerna
  - lerna bootstrap
script: yarn test
