"use strict";

var _banner = _interopRequireDefault(require("./banner"));

var _global = _interopRequireDefault(require("./global"));

var _pkg = _interopRequireDefault(require("./pkg"));

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

/** ************************************************************
  * ************************************************************
  * ***                                                      ***
  * ***  Automatically generated ** DO NOT ALTER THE BANNER  ***
  * ***                                                      ***
  * ************************************************************
  * ************************************************************ */
// this file is generated by the build process Mon Aug 27 2018 10:02:02 GMT+0300 (EEST)
module.exports = {
  banner: _banner.default,
  global: _global.default,
  pkg: _pkg.default
};
//# sourceMappingURL=index.js.map
